
name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore src/Pepegov.MicroserviceFramerwork/Pepegov.MicroserviceFramerwork.sln
    - name: Build
      run: dotnet build src/Pepegov.MicroserviceFramerwork/Pepegov.MicroserviceFramerwork.sln --configuration Release --no-restore 
    - name: Publish Pepegov.MicroserviceFramerwork
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Pepegov.MicroserviceFramerwork/Pepegov.MicroserviceFramerwork/Pepegov.MicroserviceFramerwork.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
